version: '3.8'

services: 
  postgres:
    image: postgres:16
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: phantom
      POSTGRES_PASSWORD: phantom@8526
      POSTGRES_DB: event_management
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_service
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      # DB CONFIG
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: phantom
      DB_PASSWORD: phantom@8526
      DB_NAME: event_management
      DB_SYNC: "true"
      DB_LOGGING: "true"

      # REDIS
      REDIS_URL: redis://redis:6379

      # JWT
      JWT_ACCESS_TOKEN_SECRET: "this is a secret key"
      JWT_REFRESH_TOKEN_SECRET: "this is a secret key"
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 2h
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 4d

      # RATE LIMIT
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 45

    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["pnpm", "start:prod"]

volumes:
  pg_data:
  redis_data:
