@url = http://localhost:3000
##createUser
###
POST {{url}}/users
Content-Type: application/json

{
  "first_name":"shakirah",
  "last_name":"muthoni",
  "email":"shakirah8526@duck.com",
  "phone":"0712544200",
  "role":"admin",
  "password":"shakirah@8526"
}


## for all users
###
GET {{url}}/users
### search email
GET {{url}}/users?email=alice@example.com

## for one user
###
GET {{url}}/users/ec64b9ef-fc10-4839-a36b-5eda25417d43

###detailed user
GET {{url}}/users/bb7c184e-fcf6-4ec6-b98e-664c6c79c2be?detailed=true

###
PATCH {{url}}/users/ec64b9ef-fc10-4839-a36b-5eda25417d43
Content-Type: application/json

{
  "last_name":"muthoni"
}