@url = http://localhost:3000
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmJkMDlkNi1lYjhjLTRkNDktOTJkYi05MGE0MmQ4YWFmOGQiLCJlbWFpbCI6ImZlbGl4QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ5MTEyNTM1LCJleHAiOjE3NDkxMTM3MzV9.NxIuKHjcE-hWAUYva5yaUabcprONBEaNOjNrqJyA9e0
# @refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YmYwOTk5Yi01MmViLTRjMTItYjg0NS1lZDJkY2JiMTE2MzEiLCJlbWFpbCI6Im1hcnkyMUBkdWNrLmNvbSIsImlhdCI6MTc0OTEwODM3NiwiZXhwIjoxNzQ5NDUzOTc2fQ.c5BJMcXPRbidZkYzbhc9Qc26cgDzYLF2l2w90oFXXWk
##createUser
###
POST {{url}}/users
Content-Type: application/json

{
  "first_name":"mary1",
  "email":"mary21@duck.com",
  "phone":"0712544200",
  "password":"mary@8526"
}


## for all users
###
GET {{url}}/users
Authorization: Bearer {{access_token}}

### search email
GET {{url}}/users?email=alice@example.com

## for one user
###
GET {{url}}/users/ebdec6b3-f124-46f6-a84d-60b3eeb2f009
Authorization: Bearer {{access_token}}

###detailed user
GET {{url}}/users/bb7c184e-fcf6-4ec6-b98e-664c6c79c2be?detailed=true

###
PATCH {{url}}/users/60a17254-de4c-4462-8eaf-0edd2e92d07e
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "password":"alice1234"
}

###
DELETE  {{url}}/users/ffbd09d6-eb8c-4d49-92db-90a42d8aaf8d