@url = http://localhost:3000
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExNzI1NC1kZTRjLTQ0NjItOGVhZi0wZWRkMmU5MmQwN2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ5MTE4MTk0LCJleHAiOjE3NDkxMTkzOTR9.k47wUnTFAgagAp6xlTCg0oNrOp9dmOcQg56NRpyxvzk

### all events
GET {{url}}/events?detailed=true
Authorization: Bearer {{access_token}}

### one event
GET {{url}}/events/bba01fd1-a05e-4268-9f9e-68e4c0e5d36a?detailed=true
Authorization: Bearer {{access_token}}


### creat an event
POST {{url}}/events
Content-Type: application/json

{
  "event_date":"2025-08-14",
  "event_name":"Teach2Give Cohort",
  "event_location":"Kirinyaga",
  "createdById":"ec64b9ef-fc10-4839-a36b-5eda25417d43",
  "event_description":"this event is about getting trained on web development concepts"
}
