@url=http://localhost:8000

@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExNzI1NC1kZTRjLTQ0NjItOGVhZi0wZWRkMmU5MmQwN2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ5MTE4MDIwLCJleHAiOjE3NDkxMTkyMjB9.xzsYdDyPKrxCnbJ87NoQxQAEaY_eCHTrrO3GNWJ-ACI"
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExNzI1NC1kZTRjLTQ0NjItOGVhZi0wZWRkMmU5MmQwN2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ5NjQzNzMyLCJleHAiOjE3NDk2NDQ5MzJ9.yX2N1eRazOcdfh7OGwVvYpUsSk0kDJbujAasm9hT6NE
###
POST  {{url}}/auth/login
Content-Type: application/json

{
  "email":"alice@example.com",
  "password":"alice1234"
}
### "password":"mary@8526"

###
POST {{url}}/auth/refresh/access
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refreshToken":"{{refresh_token}}"
}
###
POST {{url}}/auth/refresh
Content-Type: application/json
Authorization: Bearer  {{refresh_token}}

{
  "refresh_token": "{{refresh_token}}"
}

