@url=http://localhost:3000

@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExNzI1NC1kZTRjLTQ0NjItOGVhZi0wZWRkMmU5MmQwN2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ5MTE4MDIwLCJleHAiOjE3NDkxMTkyMjB9.xzsYdDyPKrxCnbJ87NoQxQAEaY_eCHTrrO3GNWJ-ACI"
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExNzI1NC1kZTRjLTQ0NjItOGVhZi0wZWRkMmU5MmQwN2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ5MTE4MDIwLCJleHAiOjE3NDk0NjM2MjB9.QOiPbtX0-7qd6cGSoiAaYkZlxrQ9-B4rZR5-PyDo4xg
###
POST  {{url}}/auth/login
Content-Type: application/json

{
  "email":"felix@example.com",
  "password":"felix1234"
}
### "password":"mary@8526"

###
POST {{url}}/auth/refresh/access
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refreshToken":"{{refresh_token}}"
}
###
POST {{url}}/auth/refresh
Content-Type: application/json
Authorization: Bearer  {{refresh_token}}

{
  "token": "{{refresh_token}}"
}

