@url=http://localhost:3000

@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YmYwOTk5Yi01MmViLTRjMTItYjg0NS1lZDJkY2JiMTE2MzEiLCJlbWFpbCI6Im1hcnkyMUBkdWNrLmNvbSIsImlhdCI6MTc0OTA3NzkwNywiZXhwIjoxNzQ5MDc5MTA3fQ._XqMMAbgVCeqzCi8968U1wfIegD7YZgE1UAzhNkcQIM
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YmYwOTk5Yi01MmViLTRjMTItYjg0NS1lZDJkY2JiMTE2MzEiLCJlbWFpbCI6Im1hcnkyMUBkdWNrLmNvbSIsImlhdCI6MTc0OTA3NzkwNywiZXhwIjoxNzQ5NDIzNTA3fQ.yek2yV3uf7yLez2tqOKj654abLOkIRca9POx0A57ZKY

###
POST  {{url}}/auth/login
Content-Type: application/json

{
  "email":"mary21@duck.com",
  "password":"mary@8526"
}

###
POST {{url}}/auth/refresh/access
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refreshToken":"{{refresh_token}}"
}
###
POST {{url}}/auth/refresh
Content-Type: application/json
Authorization: Bearer  {{refresh_token}}

{
  "token": "{{refresh_token}}"
}

